//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.portalfiscal.inf.br/nfe")]
[System.Xml.Serialization.XmlRootAttribute("ConsCad", Namespace="http://www.portalfiscal.inf.br/nfe", IsNullable=false)]
public partial class TConsCad {
    
    private TConsCadInfCons infConsField;
    
    private string versaoField;
    
    /// <remarks/>
    public TConsCadInfCons infCons {
        get {
            return this.infConsField;
        }
        set {
            this.infConsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string versao {
        get {
            return this.versaoField;
        }
        set {
            this.versaoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
public partial class TConsCadInfCons {
    
    private TConsCadInfConsXServ xServField;
    
    private TUfCons ufField;
    
    private string itemField;
    
    private ItemChoiceType itemElementNameField;
    
    /// <remarks/>
    public TConsCadInfConsXServ xServ {
        get {
            return this.xServField;
        }
        set {
            this.xServField = value;
        }
    }
    
    /// <remarks/>
    public TUfCons UF {
        get {
            return this.ufField;
        }
        set {
            this.ufField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CNPJ", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("CPF", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("IE", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
public enum TConsCadInfConsXServ {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("CONS-CAD")]
    CONSCAD,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.portalfiscal.inf.br/nfe")]
public enum TUfCons {
    
    /// <remarks/>
    AC,
    
    /// <remarks/>
    AL,
    
    /// <remarks/>
    AM,
    
    /// <remarks/>
    AP,
    
    /// <remarks/>
    BA,
    
    /// <remarks/>
    CE,
    
    /// <remarks/>
    DF,
    
    /// <remarks/>
    ES,
    
    /// <remarks/>
    GO,
    
    /// <remarks/>
    MA,
    
    /// <remarks/>
    MG,
    
    /// <remarks/>
    MS,
    
    /// <remarks/>
    MT,
    
    /// <remarks/>
    PA,
    
    /// <remarks/>
    PB,
    
    /// <remarks/>
    PE,
    
    /// <remarks/>
    PI,
    
    /// <remarks/>
    PR,
    
    /// <remarks/>
    RJ,
    
    /// <remarks/>
    RN,
    
    /// <remarks/>
    RO,
    
    /// <remarks/>
    RR,
    
    /// <remarks/>
    RS,
    
    /// <remarks/>
    SC,
    
    /// <remarks/>
    SE,
    
    /// <remarks/>
    SP,
    
    /// <remarks/>
    TO,
    
    /// <remarks/>
    SU,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.portalfiscal.inf.br/nfe", IncludeInSchema=false)]
public enum ItemChoiceType {
    
    /// <remarks/>
    CNPJ,
    
    /// <remarks/>
    CPF,
    
    /// <remarks/>
    IE,
}
