//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.portalfiscal.inf.br/nfe")]
[System.Xml.Serialization.XmlRootAttribute("envEvento", Namespace="http://www.portalfiscal.inf.br/nfe", IsNullable=false)]
public partial class TEnvEvento {
    
    private string idLoteField;
    
    private TEvento[] eventoField;
    
    private string versaoField;
    
    /// <remarks/>
    public string idLote {
        get {
            return this.idLoteField;
        }
        set {
            this.idLoteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("evento")]
    public TEvento[] evento {
        get {
            return this.eventoField;
        }
        set {
            this.eventoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string versao {
        get {
            return this.versaoField;
        }
        set {
            this.versaoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.portalfiscal.inf.br/nfe")]
public partial class TEvento {
    
    private TEventoInfEvento infEventoField;
    
    private string versaoField;
    
    /// <remarks/>
    public TEventoInfEvento infEvento {
        get {
            return this.infEventoField;
        }
        set {
            this.infEventoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string versao {
        get {
            return this.versaoField;
        }
        set {
            this.versaoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
public partial class TEventoInfEvento {
    
    private TCOrgaoIBGE cOrgaoField;
    
    private TAmb tpAmbField;
    
    private string itemField;
    
    private ItemChoiceType itemElementNameField;
    
    private string chNFeField;
    
    private string dhEventoField;
    
    private TEventoInfEventoTpEvento tpEventoField;
    
    private string nSeqEventoField;
    
    private TEventoInfEventoVerEvento verEventoField;
    
    private TEventoInfEventoDetEvento detEventoField;
    
    private string idField;
    
    /// <remarks/>
    public TCOrgaoIBGE cOrgao {
        get {
            return this.cOrgaoField;
        }
        set {
            this.cOrgaoField = value;
        }
    }
    
    /// <remarks/>
    public TAmb tpAmb {
        get {
            return this.tpAmbField;
        }
        set {
            this.tpAmbField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CNPJ", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("CPF", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
    
    /// <remarks/>
    public string chNFe {
        get {
            return this.chNFeField;
        }
        set {
            this.chNFeField = value;
        }
    }
    
    /// <remarks/>
    public string dhEvento {
        get {
            return this.dhEventoField;
        }
        set {
            this.dhEventoField = value;
        }
    }
    
    /// <remarks/>
    public TEventoInfEventoTpEvento tpEvento {
        get {
            return this.tpEventoField;
        }
        set {
            this.tpEventoField = value;
        }
    }
    
    /// <remarks/>
    public string nSeqEvento {
        get {
            return this.nSeqEventoField;
        }
        set {
            this.nSeqEventoField = value;
        }
    }
    
    /// <remarks/>
    public TEventoInfEventoVerEvento verEvento {
        get {
            return this.verEventoField;
        }
        set {
            this.verEventoField = value;
        }
    }
    
    /// <remarks/>
    public TEventoInfEventoDetEvento detEvento {
        get {
            return this.detEventoField;
        }
        set {
            this.detEventoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.portalfiscal.inf.br/nfe")]
public enum TCOrgaoIBGE {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("11")]
    Item11,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("12")]
    Item12,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("13")]
    Item13,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("14")]
    Item14,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("15")]
    Item15,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("16")]
    Item16,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("17")]
    Item17,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("21")]
    Item21,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("22")]
    Item22,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("23")]
    Item23,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("24")]
    Item24,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("25")]
    Item25,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("26")]
    Item26,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("27")]
    Item27,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("28")]
    Item28,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("29")]
    Item29,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("31")]
    Item31,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("32")]
    Item32,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("33")]
    Item33,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("35")]
    Item35,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("41")]
    Item41,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("42")]
    Item42,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("43")]
    Item43,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("50")]
    Item50,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("51")]
    Item51,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("52")]
    Item52,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("53")]
    Item53,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("90")]
    Item90,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("91")]
    Item91,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("92")]
    Item92,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.portalfiscal.inf.br/nfe")]
public enum TAmb {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.portalfiscal.inf.br/nfe", IncludeInSchema=false)]
public enum ItemChoiceType {
    
    /// <remarks/>
    CNPJ,
    
    /// <remarks/>
    CPF,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
public enum TEventoInfEventoTpEvento {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("110111")]
    Item110111,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
public enum TEventoInfEventoVerEvento {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1.00")]
    Item100,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
public partial class TEventoInfEventoDetEvento {
    
    private TEventoInfEventoDetEventoDescEvento descEventoField;
    
    private string nProtField;
    
    private string xJustField;
    
    private TEventoInfEventoDetEventoVersao versaoField;
    
    /// <remarks/>
    public TEventoInfEventoDetEventoDescEvento descEvento {
        get {
            return this.descEventoField;
        }
        set {
            this.descEventoField = value;
        }
    }
    
    /// <remarks/>
    public string nProt {
        get {
            return this.nProtField;
        }
        set {
            this.nProtField = value;
        }
    }
    
    /// <remarks/>
    public string xJust {
        get {
            return this.xJustField;
        }
        set {
            this.xJustField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public TEventoInfEventoDetEventoVersao versao {
        get {
            return this.versaoField;
        }
        set {
            this.versaoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
public enum TEventoInfEventoDetEventoDescEvento {
    
    /// <remarks/>
    Cancelamento,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
public enum TEventoInfEventoDetEventoVersao {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1.00")]
    Item100,
}
