//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFSe.bethaConsultarSituacaoLoteRPS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws", ConfigurationName="bethaConsultarSituacaoLoteRPS.ConsultarSituacaoLoteRps")]
    public interface ConsultarSituacaoLoteRps {
        
        // CODEGEN: Generating message contract since the operation ConsultarSituacaoLoteRpsEnvio is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        NFSe.bethaConsultarSituacaoLoteRPS.ConsultarSituacaoLoteRpsEnvioResponse1 ConsultarSituacaoLoteRpsEnvio(NFSe.bethaConsultarSituacaoLoteRPS.ConsultarSituacaoLoteRpsEnvioRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class ConsultarSituacaoLoteRpsEnvio : object, System.ComponentModel.INotifyPropertyChanged {
        
        private tcIdentificacaoPrestador prestadorField;
        
        private string protocoloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public tcIdentificacaoPrestador Prestador {
            get {
                return this.prestadorField;
            }
            set {
                this.prestadorField = value;
                this.RaisePropertyChanged("Prestador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=1)]
        public string Protocolo {
            get {
                return this.protocoloField;
            }
            set {
                this.protocoloField = value;
                this.RaisePropertyChanged("Protocolo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcIdentificacaoPrestador : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cnpjField;
        
        private string inscricaoMunicipalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Cnpj {
            get {
                return this.cnpjField;
            }
            set {
                this.cnpjField = value;
                this.RaisePropertyChanged("Cnpj");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string InscricaoMunicipal {
            get {
                return this.inscricaoMunicipalField;
            }
            set {
                this.inscricaoMunicipalField = value;
                this.RaisePropertyChanged("InscricaoMunicipal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcMensagemRetorno : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string mensagemField;
        
        private string correcaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("Codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
                this.RaisePropertyChanged("Mensagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Correcao {
            get {
                return this.correcaoField;
            }
            set {
                this.correcaoField = value;
                this.RaisePropertyChanged("Correcao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class consultarSituacaoLoteRpsResposta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroLoteField;
        
        private string situacaoField;
        
        private tcMensagemRetorno[] listaMensagemRetornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=0)]
        public string NumeroLote {
            get {
                return this.numeroLoteField;
            }
            set {
                this.numeroLoteField = value;
                this.RaisePropertyChanged("NumeroLote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Situacao {
            get {
                return this.situacaoField;
            }
            set {
                this.situacaoField = value;
                this.RaisePropertyChanged("Situacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("MensagemRetorno", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public tcMensagemRetorno[] ListaMensagemRetorno {
            get {
                return this.listaMensagemRetornoField;
            }
            set {
                this.listaMensagemRetornoField = value;
                this.RaisePropertyChanged("ListaMensagemRetorno");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class ConsultarSituacaoLoteRpsEnvioResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private consultarSituacaoLoteRpsResposta consultarSituacaoLoteRpsRespostaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public consultarSituacaoLoteRpsResposta ConsultarSituacaoLoteRpsResposta {
            get {
                return this.consultarSituacaoLoteRpsRespostaField;
            }
            set {
                this.consultarSituacaoLoteRpsRespostaField = value;
                this.RaisePropertyChanged("ConsultarSituacaoLoteRpsResposta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarSituacaoLoteRpsEnvioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws", Order=0)]
        public NFSe.bethaConsultarSituacaoLoteRPS.ConsultarSituacaoLoteRpsEnvio ConsultarSituacaoLoteRpsEnvio;
        
        public ConsultarSituacaoLoteRpsEnvioRequest() {
        }
        
        public ConsultarSituacaoLoteRpsEnvioRequest(NFSe.bethaConsultarSituacaoLoteRPS.ConsultarSituacaoLoteRpsEnvio ConsultarSituacaoLoteRpsEnvio) {
            this.ConsultarSituacaoLoteRpsEnvio = ConsultarSituacaoLoteRpsEnvio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarSituacaoLoteRpsEnvioResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws", Order=0)]
        public NFSe.bethaConsultarSituacaoLoteRPS.ConsultarSituacaoLoteRpsEnvioResponse ConsultarSituacaoLoteRpsEnvioResponse;
        
        public ConsultarSituacaoLoteRpsEnvioResponse1() {
        }
        
        public ConsultarSituacaoLoteRpsEnvioResponse1(NFSe.bethaConsultarSituacaoLoteRPS.ConsultarSituacaoLoteRpsEnvioResponse ConsultarSituacaoLoteRpsEnvioResponse) {
            this.ConsultarSituacaoLoteRpsEnvioResponse = ConsultarSituacaoLoteRpsEnvioResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ConsultarSituacaoLoteRpsChannel : NFSe.bethaConsultarSituacaoLoteRPS.ConsultarSituacaoLoteRps, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ConsultarSituacaoLoteRpsClient : System.ServiceModel.ClientBase<NFSe.bethaConsultarSituacaoLoteRPS.ConsultarSituacaoLoteRps>, NFSe.bethaConsultarSituacaoLoteRPS.ConsultarSituacaoLoteRps {
        
        public ConsultarSituacaoLoteRpsClient() {
        }
        
        public ConsultarSituacaoLoteRpsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultarSituacaoLoteRpsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultarSituacaoLoteRpsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultarSituacaoLoteRpsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NFSe.bethaConsultarSituacaoLoteRPS.ConsultarSituacaoLoteRpsEnvioResponse1 NFSe.bethaConsultarSituacaoLoteRPS.ConsultarSituacaoLoteRps.ConsultarSituacaoLoteRpsEnvio(NFSe.bethaConsultarSituacaoLoteRPS.ConsultarSituacaoLoteRpsEnvioRequest request) {
            return base.Channel.ConsultarSituacaoLoteRpsEnvio(request);
        }
        
        public NFSe.bethaConsultarSituacaoLoteRPS.ConsultarSituacaoLoteRpsEnvioResponse ConsultarSituacaoLoteRpsEnvio(NFSe.bethaConsultarSituacaoLoteRPS.ConsultarSituacaoLoteRpsEnvio ConsultarSituacaoLoteRpsEnvio1) {
            NFSe.bethaConsultarSituacaoLoteRPS.ConsultarSituacaoLoteRpsEnvioRequest inValue = new NFSe.bethaConsultarSituacaoLoteRPS.ConsultarSituacaoLoteRpsEnvioRequest();
            inValue.ConsultarSituacaoLoteRpsEnvio = ConsultarSituacaoLoteRpsEnvio1;
            NFSe.bethaConsultarSituacaoLoteRPS.ConsultarSituacaoLoteRpsEnvioResponse1 retVal = ((NFSe.bethaConsultarSituacaoLoteRPS.ConsultarSituacaoLoteRps)(this)).ConsultarSituacaoLoteRpsEnvio(inValue);
            return retVal.ConsultarSituacaoLoteRpsEnvioResponse;
        }
    }
}
