//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFSe.bethaRecepcionarLoteRPS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws", ConfigurationName="bethaRecepcionarLoteRPS.RecepcionarLoteRps")]
    public interface RecepcionarLoteRps {
        
        // CODEGEN: Generating message contract since the operation EnviarLoteRpsEnvio is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        NFSe.bethaRecepcionarLoteRPS.EnviarLoteRpsEnvioResponse1 EnviarLoteRpsEnvio(NFSe.bethaRecepcionarLoteRPS.EnviarLoteRpsEnvioRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class EnviarLoteRpsEnvio : object, System.ComponentModel.INotifyPropertyChanged {
        
        private tcLoteRps loteRpsField;
        
        private Signature signatureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public tcLoteRps LoteRps {
            get {
                return this.loteRpsField;
            }
            set {
                this.loteRpsField = value;
                this.RaisePropertyChanged("LoteRps");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", Order=1)]
        public Signature Signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
                this.RaisePropertyChanged("Signature");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcLoteRps : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long numeroLoteField;
        
        private string cnpjField;
        
        private string inscricaoMunicipalField;
        
        private int quantidadeRpsField;
        
        private tcRps[] listaRpsField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long NumeroLote {
            get {
                return this.numeroLoteField;
            }
            set {
                this.numeroLoteField = value;
                this.RaisePropertyChanged("NumeroLote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Cnpj {
            get {
                return this.cnpjField;
            }
            set {
                this.cnpjField = value;
                this.RaisePropertyChanged("Cnpj");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string InscricaoMunicipal {
            get {
                return this.inscricaoMunicipalField;
            }
            set {
                this.inscricaoMunicipalField = value;
                this.RaisePropertyChanged("InscricaoMunicipal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int QuantidadeRps {
            get {
                return this.quantidadeRpsField;
            }
            set {
                this.quantidadeRpsField = value;
                this.RaisePropertyChanged("QuantidadeRps");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Rps", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public tcRps[] ListaRps {
            get {
                return this.listaRpsField;
            }
            set {
                this.listaRpsField = value;
                this.RaisePropertyChanged("ListaRps");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcRps : object, System.ComponentModel.INotifyPropertyChanged {
        
        private tcInfRps infRpsField;
        
        private Signature signatureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public tcInfRps InfRps {
            get {
                return this.infRpsField;
            }
            set {
                this.infRpsField = value;
                this.RaisePropertyChanged("InfRps");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", Order=1)]
        public Signature Signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
                this.RaisePropertyChanged("Signature");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcInfRps : object, System.ComponentModel.INotifyPropertyChanged {
        
        private tcIdentificacaoRps identificacaoRpsField;
        
        private System.DateTime dataEmissaoField;
        
        private int naturezaOperacaoField;
        
        private int regimeEspecialTributacaoField;
        
        private bool regimeEspecialTributacaoFieldSpecified;
        
        private int optanteSimplesNacionalField;
        
        private int incentivadorCulturalField;
        
        private int statusField;
        
        private tcIdentificacaoRps rpsSubstituidoField;
        
        private tcDadosServico servicoField;
        
        private tcIdentificacaoPrestador prestadorField;
        
        private tcDadosTomador tomadorField;
        
        private tcIdentificacaoIntermediarioServico intermediarioServicoField;
        
        private tcDadosConstrucaoCivil construcaoCivilField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public tcIdentificacaoRps IdentificacaoRps {
            get {
                return this.identificacaoRpsField;
            }
            set {
                this.identificacaoRpsField = value;
                this.RaisePropertyChanged("IdentificacaoRps");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime DataEmissao {
            get {
                return this.dataEmissaoField;
            }
            set {
                this.dataEmissaoField = value;
                this.RaisePropertyChanged("DataEmissao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int NaturezaOperacao {
            get {
                return this.naturezaOperacaoField;
            }
            set {
                this.naturezaOperacaoField = value;
                this.RaisePropertyChanged("NaturezaOperacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int RegimeEspecialTributacao {
            get {
                return this.regimeEspecialTributacaoField;
            }
            set {
                this.regimeEspecialTributacaoField = value;
                this.RaisePropertyChanged("RegimeEspecialTributacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RegimeEspecialTributacaoSpecified {
            get {
                return this.regimeEspecialTributacaoFieldSpecified;
            }
            set {
                this.regimeEspecialTributacaoFieldSpecified = value;
                this.RaisePropertyChanged("RegimeEspecialTributacaoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int OptanteSimplesNacional {
            get {
                return this.optanteSimplesNacionalField;
            }
            set {
                this.optanteSimplesNacionalField = value;
                this.RaisePropertyChanged("OptanteSimplesNacional");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int IncentivadorCultural {
            get {
                return this.incentivadorCulturalField;
            }
            set {
                this.incentivadorCulturalField = value;
                this.RaisePropertyChanged("IncentivadorCultural");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public tcIdentificacaoRps RpsSubstituido {
            get {
                return this.rpsSubstituidoField;
            }
            set {
                this.rpsSubstituidoField = value;
                this.RaisePropertyChanged("RpsSubstituido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public tcDadosServico Servico {
            get {
                return this.servicoField;
            }
            set {
                this.servicoField = value;
                this.RaisePropertyChanged("Servico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public tcIdentificacaoPrestador Prestador {
            get {
                return this.prestadorField;
            }
            set {
                this.prestadorField = value;
                this.RaisePropertyChanged("Prestador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public tcDadosTomador Tomador {
            get {
                return this.tomadorField;
            }
            set {
                this.tomadorField = value;
                this.RaisePropertyChanged("Tomador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public tcIdentificacaoIntermediarioServico IntermediarioServico {
            get {
                return this.intermediarioServicoField;
            }
            set {
                this.intermediarioServicoField = value;
                this.RaisePropertyChanged("IntermediarioServico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public tcDadosConstrucaoCivil ConstrucaoCivil {
            get {
                return this.construcaoCivilField;
            }
            set {
                this.construcaoCivilField = value;
                this.RaisePropertyChanged("ConstrucaoCivil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcIdentificacaoRps : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int numeroField;
        
        private string serieField;
        
        private int tipoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("Numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Serie {
            get {
                return this.serieField;
            }
            set {
                this.serieField = value;
                this.RaisePropertyChanged("Serie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("Tipo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcMensagemRetorno : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string mensagemField;
        
        private string correcaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("Codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
                this.RaisePropertyChanged("Mensagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Correcao {
            get {
                return this.correcaoField;
            }
            set {
                this.correcaoField = value;
                this.RaisePropertyChanged("Correcao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class enviarLoteRpsResposta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroLoteField;
        
        private System.DateTime dataRecebimentoField;
        
        private bool dataRecebimentoFieldSpecified;
        
        private string protocoloField;
        
        private tcMensagemRetorno[] listaMensagemRetornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=0)]
        public string NumeroLote {
            get {
                return this.numeroLoteField;
            }
            set {
                this.numeroLoteField = value;
                this.RaisePropertyChanged("NumeroLote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime DataRecebimento {
            get {
                return this.dataRecebimentoField;
            }
            set {
                this.dataRecebimentoField = value;
                this.RaisePropertyChanged("DataRecebimento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataRecebimentoSpecified {
            get {
                return this.dataRecebimentoFieldSpecified;
            }
            set {
                this.dataRecebimentoFieldSpecified = value;
                this.RaisePropertyChanged("DataRecebimentoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=2)]
        public string Protocolo {
            get {
                return this.protocoloField;
            }
            set {
                this.protocoloField = value;
                this.RaisePropertyChanged("Protocolo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("MensagemRetorno", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public tcMensagemRetorno[] ListaMensagemRetorno {
            get {
                return this.listaMensagemRetornoField;
            }
            set {
                this.listaMensagemRetornoField = value;
                this.RaisePropertyChanged("ListaMensagemRetorno");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class EnviarLoteRpsEnvioResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private enviarLoteRpsResposta enviarLoteRpsRespostaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public enviarLoteRpsResposta EnviarLoteRpsResposta {
            get {
                return this.enviarLoteRpsRespostaField;
            }
            set {
                this.enviarLoteRpsRespostaField = value;
                this.RaisePropertyChanged("EnviarLoteRpsResposta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class tcX509Data : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string x509CertificateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string X509Certificate {
            get {
                return this.x509CertificateField;
            }
            set {
                this.x509CertificateField = value;
                this.RaisePropertyChanged("X509Certificate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcKeyInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private tcX509Data x509DataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", Order=0)]
        public tcX509Data X509Data {
            get {
                return this.x509DataField;
            }
            set {
                this.x509DataField = value;
                this.RaisePropertyChanged("X509Data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class tcDigestMethod : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
                this.RaisePropertyChanged("Algorithm");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcTransform : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
                this.RaisePropertyChanged("Algorithm");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcReference : object, System.ComponentModel.INotifyPropertyChanged {
        
        private tcTransform[] transformsField;
        
        private tcDigestMethod digestMethodField;
        
        private string digestValueField;
        
        private string uRIField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable=false)]
        public tcTransform[] Transforms {
            get {
                return this.transformsField;
            }
            set {
                this.transformsField = value;
                this.RaisePropertyChanged("Transforms");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", Order=1)]
        public tcDigestMethod DigestMethod {
            get {
                return this.digestMethodField;
            }
            set {
                this.digestMethodField = value;
                this.RaisePropertyChanged("DigestMethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", Order=2)]
        public string DigestValue {
            get {
                return this.digestValueField;
            }
            set {
                this.digestValueField = value;
                this.RaisePropertyChanged("DigestValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string URI {
            get {
                return this.uRIField;
            }
            set {
                this.uRIField = value;
                this.RaisePropertyChanged("URI");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class tcSignatureMethod : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
                this.RaisePropertyChanged("Algorithm");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class tcCanonicalizationMethod : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
                this.RaisePropertyChanged("Algorithm");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcSigInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private tcCanonicalizationMethod canonicalizationMethodField;
        
        private tcSignatureMethod signatureMethodField;
        
        private tcReference referenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", Order=0)]
        public tcCanonicalizationMethod CanonicalizationMethod {
            get {
                return this.canonicalizationMethodField;
            }
            set {
                this.canonicalizationMethodField = value;
                this.RaisePropertyChanged("CanonicalizationMethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", Order=1)]
        public tcSignatureMethod SignatureMethod {
            get {
                return this.signatureMethodField;
            }
            set {
                this.signatureMethodField = value;
                this.RaisePropertyChanged("SignatureMethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", Order=2)]
        public tcReference Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
                this.RaisePropertyChanged("Reference");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class Signature : object, System.ComponentModel.INotifyPropertyChanged {
        
        private tcSigInfo signedInfoField;
        
        private string signatureValueField;
        
        private tcKeyInfo keyInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public tcSigInfo SignedInfo {
            get {
                return this.signedInfoField;
            }
            set {
                this.signedInfoField = value;
                this.RaisePropertyChanged("SignedInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SignatureValue {
            get {
                return this.signatureValueField;
            }
            set {
                this.signatureValueField = value;
                this.RaisePropertyChanged("SignatureValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public tcKeyInfo KeyInfo {
            get {
                return this.keyInfoField;
            }
            set {
                this.keyInfoField = value;
                this.RaisePropertyChanged("KeyInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcDadosConstrucaoCivil : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoObraField;
        
        private string artField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CodigoObra {
            get {
                return this.codigoObraField;
            }
            set {
                this.codigoObraField = value;
                this.RaisePropertyChanged("CodigoObra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Art {
            get {
                return this.artField;
            }
            set {
                this.artField = value;
                this.RaisePropertyChanged("Art");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcIdentificacaoIntermediarioServico : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string razaoSocialField;
        
        private tcCpfCnpj cpfCnpjField;
        
        private string inscricaoMunicipalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string RazaoSocial {
            get {
                return this.razaoSocialField;
            }
            set {
                this.razaoSocialField = value;
                this.RaisePropertyChanged("RazaoSocial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public tcCpfCnpj CpfCnpj {
            get {
                return this.cpfCnpjField;
            }
            set {
                this.cpfCnpjField = value;
                this.RaisePropertyChanged("CpfCnpj");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string InscricaoMunicipal {
            get {
                return this.inscricaoMunicipalField;
            }
            set {
                this.inscricaoMunicipalField = value;
                this.RaisePropertyChanged("InscricaoMunicipal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcCpfCnpj : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cnpjField;
        
        private string cpfField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Cnpj {
            get {
                return this.cnpjField;
            }
            set {
                this.cnpjField = value;
                this.RaisePropertyChanged("Cnpj");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
                this.RaisePropertyChanged("Cpf");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcContato : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string telefoneField;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
                this.RaisePropertyChanged("Telefone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcEndereco : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string enderecoField;
        
        private string numeroField;
        
        private string complementoField;
        
        private string bairroField;
        
        private int codigoMunicipioField;
        
        private bool codigoMunicipioFieldSpecified;
        
        private string ufField;
        
        private int cepField;
        
        private bool cepFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
                this.RaisePropertyChanged("Endereco");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("Numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Complemento {
            get {
                return this.complementoField;
            }
            set {
                this.complementoField = value;
                this.RaisePropertyChanged("Complemento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
                this.RaisePropertyChanged("Bairro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int CodigoMunicipio {
            get {
                return this.codigoMunicipioField;
            }
            set {
                this.codigoMunicipioField = value;
                this.RaisePropertyChanged("CodigoMunicipio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodigoMunicipioSpecified {
            get {
                return this.codigoMunicipioFieldSpecified;
            }
            set {
                this.codigoMunicipioFieldSpecified = value;
                this.RaisePropertyChanged("CodigoMunicipioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Uf {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
                this.RaisePropertyChanged("Uf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int Cep {
            get {
                return this.cepField;
            }
            set {
                this.cepField = value;
                this.RaisePropertyChanged("Cep");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CepSpecified {
            get {
                return this.cepFieldSpecified;
            }
            set {
                this.cepFieldSpecified = value;
                this.RaisePropertyChanged("CepSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcIdentificacaoTomador : object, System.ComponentModel.INotifyPropertyChanged {
        
        private tcCpfCnpj cpfCnpjField;
        
        private string inscricaoMunicipalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public tcCpfCnpj CpfCnpj {
            get {
                return this.cpfCnpjField;
            }
            set {
                this.cpfCnpjField = value;
                this.RaisePropertyChanged("CpfCnpj");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string InscricaoMunicipal {
            get {
                return this.inscricaoMunicipalField;
            }
            set {
                this.inscricaoMunicipalField = value;
                this.RaisePropertyChanged("InscricaoMunicipal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcDadosTomador : object, System.ComponentModel.INotifyPropertyChanged {
        
        private tcIdentificacaoTomador identificacaoTomadorField;
        
        private string razaoSocialField;
        
        private tcEndereco enderecoField;
        
        private tcContato contatoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public tcIdentificacaoTomador IdentificacaoTomador {
            get {
                return this.identificacaoTomadorField;
            }
            set {
                this.identificacaoTomadorField = value;
                this.RaisePropertyChanged("IdentificacaoTomador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string RazaoSocial {
            get {
                return this.razaoSocialField;
            }
            set {
                this.razaoSocialField = value;
                this.RaisePropertyChanged("RazaoSocial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public tcEndereco Endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
                this.RaisePropertyChanged("Endereco");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public tcContato Contato {
            get {
                return this.contatoField;
            }
            set {
                this.contatoField = value;
                this.RaisePropertyChanged("Contato");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcIdentificacaoPrestador : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cnpjField;
        
        private string inscricaoMunicipalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Cnpj {
            get {
                return this.cnpjField;
            }
            set {
                this.cnpjField = value;
                this.RaisePropertyChanged("Cnpj");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string InscricaoMunicipal {
            get {
                return this.inscricaoMunicipalField;
            }
            set {
                this.inscricaoMunicipalField = value;
                this.RaisePropertyChanged("InscricaoMunicipal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcValores : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal valorServicosField;
        
        private decimal valorDeducoesField;
        
        private bool valorDeducoesFieldSpecified;
        
        private decimal valorPisField;
        
        private bool valorPisFieldSpecified;
        
        private decimal valorCofinsField;
        
        private bool valorCofinsFieldSpecified;
        
        private decimal valorInssField;
        
        private bool valorInssFieldSpecified;
        
        private decimal valorIrField;
        
        private bool valorIrFieldSpecified;
        
        private decimal valorCsllField;
        
        private bool valorCsllFieldSpecified;
        
        private int issRetidoField;
        
        private bool issRetidoFieldSpecified;
        
        private decimal valorIssField;
        
        private bool valorIssFieldSpecified;
        
        private decimal outrasRetencoesField;
        
        private bool outrasRetencoesFieldSpecified;
        
        private decimal baseCalculoField;
        
        private decimal aliquotaField;
        
        private bool aliquotaFieldSpecified;
        
        private decimal valorLiquidoNfseField;
        
        private bool valorLiquidoNfseFieldSpecified;
        
        private decimal valorIssRetidoField;
        
        private bool valorIssRetidoFieldSpecified;
        
        private decimal descontoCondicionadoField;
        
        private bool descontoCondicionadoFieldSpecified;
        
        private decimal descontoIncondicionadoField;
        
        private bool descontoIncondicionadoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal ValorServicos {
            get {
                return this.valorServicosField;
            }
            set {
                this.valorServicosField = value;
                this.RaisePropertyChanged("ValorServicos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal ValorDeducoes {
            get {
                return this.valorDeducoesField;
            }
            set {
                this.valorDeducoesField = value;
                this.RaisePropertyChanged("ValorDeducoes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorDeducoesSpecified {
            get {
                return this.valorDeducoesFieldSpecified;
            }
            set {
                this.valorDeducoesFieldSpecified = value;
                this.RaisePropertyChanged("ValorDeducoesSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal ValorPis {
            get {
                return this.valorPisField;
            }
            set {
                this.valorPisField = value;
                this.RaisePropertyChanged("ValorPis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorPisSpecified {
            get {
                return this.valorPisFieldSpecified;
            }
            set {
                this.valorPisFieldSpecified = value;
                this.RaisePropertyChanged("ValorPisSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal ValorCofins {
            get {
                return this.valorCofinsField;
            }
            set {
                this.valorCofinsField = value;
                this.RaisePropertyChanged("ValorCofins");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorCofinsSpecified {
            get {
                return this.valorCofinsFieldSpecified;
            }
            set {
                this.valorCofinsFieldSpecified = value;
                this.RaisePropertyChanged("ValorCofinsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal ValorInss {
            get {
                return this.valorInssField;
            }
            set {
                this.valorInssField = value;
                this.RaisePropertyChanged("ValorInss");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorInssSpecified {
            get {
                return this.valorInssFieldSpecified;
            }
            set {
                this.valorInssFieldSpecified = value;
                this.RaisePropertyChanged("ValorInssSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal ValorIr {
            get {
                return this.valorIrField;
            }
            set {
                this.valorIrField = value;
                this.RaisePropertyChanged("ValorIr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorIrSpecified {
            get {
                return this.valorIrFieldSpecified;
            }
            set {
                this.valorIrFieldSpecified = value;
                this.RaisePropertyChanged("ValorIrSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal ValorCsll {
            get {
                return this.valorCsllField;
            }
            set {
                this.valorCsllField = value;
                this.RaisePropertyChanged("ValorCsll");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorCsllSpecified {
            get {
                return this.valorCsllFieldSpecified;
            }
            set {
                this.valorCsllFieldSpecified = value;
                this.RaisePropertyChanged("ValorCsllSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int IssRetido {
            get {
                return this.issRetidoField;
            }
            set {
                this.issRetidoField = value;
                this.RaisePropertyChanged("IssRetido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IssRetidoSpecified {
            get {
                return this.issRetidoFieldSpecified;
            }
            set {
                this.issRetidoFieldSpecified = value;
                this.RaisePropertyChanged("IssRetidoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal ValorIss {
            get {
                return this.valorIssField;
            }
            set {
                this.valorIssField = value;
                this.RaisePropertyChanged("ValorIss");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorIssSpecified {
            get {
                return this.valorIssFieldSpecified;
            }
            set {
                this.valorIssFieldSpecified = value;
                this.RaisePropertyChanged("ValorIssSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal OutrasRetencoes {
            get {
                return this.outrasRetencoesField;
            }
            set {
                this.outrasRetencoesField = value;
                this.RaisePropertyChanged("OutrasRetencoes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OutrasRetencoesSpecified {
            get {
                return this.outrasRetencoesFieldSpecified;
            }
            set {
                this.outrasRetencoesFieldSpecified = value;
                this.RaisePropertyChanged("OutrasRetencoesSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal BaseCalculo {
            get {
                return this.baseCalculoField;
            }
            set {
                this.baseCalculoField = value;
                this.RaisePropertyChanged("BaseCalculo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public decimal Aliquota {
            get {
                return this.aliquotaField;
            }
            set {
                this.aliquotaField = value;
                this.RaisePropertyChanged("Aliquota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AliquotaSpecified {
            get {
                return this.aliquotaFieldSpecified;
            }
            set {
                this.aliquotaFieldSpecified = value;
                this.RaisePropertyChanged("AliquotaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public decimal ValorLiquidoNfse {
            get {
                return this.valorLiquidoNfseField;
            }
            set {
                this.valorLiquidoNfseField = value;
                this.RaisePropertyChanged("ValorLiquidoNfse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorLiquidoNfseSpecified {
            get {
                return this.valorLiquidoNfseFieldSpecified;
            }
            set {
                this.valorLiquidoNfseFieldSpecified = value;
                this.RaisePropertyChanged("ValorLiquidoNfseSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public decimal ValorIssRetido {
            get {
                return this.valorIssRetidoField;
            }
            set {
                this.valorIssRetidoField = value;
                this.RaisePropertyChanged("ValorIssRetido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorIssRetidoSpecified {
            get {
                return this.valorIssRetidoFieldSpecified;
            }
            set {
                this.valorIssRetidoFieldSpecified = value;
                this.RaisePropertyChanged("ValorIssRetidoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public decimal DescontoCondicionado {
            get {
                return this.descontoCondicionadoField;
            }
            set {
                this.descontoCondicionadoField = value;
                this.RaisePropertyChanged("DescontoCondicionado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DescontoCondicionadoSpecified {
            get {
                return this.descontoCondicionadoFieldSpecified;
            }
            set {
                this.descontoCondicionadoFieldSpecified = value;
                this.RaisePropertyChanged("DescontoCondicionadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public decimal DescontoIncondicionado {
            get {
                return this.descontoIncondicionadoField;
            }
            set {
                this.descontoIncondicionadoField = value;
                this.RaisePropertyChanged("DescontoIncondicionado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DescontoIncondicionadoSpecified {
            get {
                return this.descontoIncondicionadoFieldSpecified;
            }
            set {
                this.descontoIncondicionadoFieldSpecified = value;
                this.RaisePropertyChanged("DescontoIncondicionadoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcDadosServico : object, System.ComponentModel.INotifyPropertyChanged {
        
        private tcValores valoresField;
        
        private string itemListaServicoField;
        
        private int codigoCnaeField;
        
        private bool codigoCnaeFieldSpecified;
        
        private string codigoTributacaoMunicipioField;
        
        private string discriminacaoField;
        
        private int codigoMunicipioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public tcValores Valores {
            get {
                return this.valoresField;
            }
            set {
                this.valoresField = value;
                this.RaisePropertyChanged("Valores");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ItemListaServico {
            get {
                return this.itemListaServicoField;
            }
            set {
                this.itemListaServicoField = value;
                this.RaisePropertyChanged("ItemListaServico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int CodigoCnae {
            get {
                return this.codigoCnaeField;
            }
            set {
                this.codigoCnaeField = value;
                this.RaisePropertyChanged("CodigoCnae");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodigoCnaeSpecified {
            get {
                return this.codigoCnaeFieldSpecified;
            }
            set {
                this.codigoCnaeFieldSpecified = value;
                this.RaisePropertyChanged("CodigoCnaeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CodigoTributacaoMunicipio {
            get {
                return this.codigoTributacaoMunicipioField;
            }
            set {
                this.codigoTributacaoMunicipioField = value;
                this.RaisePropertyChanged("CodigoTributacaoMunicipio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Discriminacao {
            get {
                return this.discriminacaoField;
            }
            set {
                this.discriminacaoField = value;
                this.RaisePropertyChanged("Discriminacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int CodigoMunicipio {
            get {
                return this.codigoMunicipioField;
            }
            set {
                this.codigoMunicipioField = value;
                this.RaisePropertyChanged("CodigoMunicipio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviarLoteRpsEnvioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws", Order=0)]
        public NFSe.bethaRecepcionarLoteRPS.EnviarLoteRpsEnvio EnviarLoteRpsEnvio;
        
        public EnviarLoteRpsEnvioRequest() {
        }
        
        public EnviarLoteRpsEnvioRequest(NFSe.bethaRecepcionarLoteRPS.EnviarLoteRpsEnvio EnviarLoteRpsEnvio) {
            this.EnviarLoteRpsEnvio = EnviarLoteRpsEnvio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviarLoteRpsEnvioResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws", Order=0)]
        public NFSe.bethaRecepcionarLoteRPS.EnviarLoteRpsEnvioResponse EnviarLoteRpsEnvioResponse;
        
        public EnviarLoteRpsEnvioResponse1() {
        }
        
        public EnviarLoteRpsEnvioResponse1(NFSe.bethaRecepcionarLoteRPS.EnviarLoteRpsEnvioResponse EnviarLoteRpsEnvioResponse) {
            this.EnviarLoteRpsEnvioResponse = EnviarLoteRpsEnvioResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface RecepcionarLoteRpsChannel : NFSe.bethaRecepcionarLoteRPS.RecepcionarLoteRps, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class RecepcionarLoteRpsClient : System.ServiceModel.ClientBase<NFSe.bethaRecepcionarLoteRPS.RecepcionarLoteRps>, NFSe.bethaRecepcionarLoteRPS.RecepcionarLoteRps {
        
        public RecepcionarLoteRpsClient() {
        }
        
        public RecepcionarLoteRpsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RecepcionarLoteRpsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecepcionarLoteRpsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecepcionarLoteRpsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NFSe.bethaRecepcionarLoteRPS.EnviarLoteRpsEnvioResponse1 NFSe.bethaRecepcionarLoteRPS.RecepcionarLoteRps.EnviarLoteRpsEnvio(NFSe.bethaRecepcionarLoteRPS.EnviarLoteRpsEnvioRequest request) {
            return base.Channel.EnviarLoteRpsEnvio(request);
        }
        
        public NFSe.bethaRecepcionarLoteRPS.EnviarLoteRpsEnvioResponse EnviarLoteRpsEnvio(NFSe.bethaRecepcionarLoteRPS.EnviarLoteRpsEnvio EnviarLoteRpsEnvio1) {
            NFSe.bethaRecepcionarLoteRPS.EnviarLoteRpsEnvioRequest inValue = new NFSe.bethaRecepcionarLoteRPS.EnviarLoteRpsEnvioRequest();
            inValue.EnviarLoteRpsEnvio = EnviarLoteRpsEnvio1;
            NFSe.bethaRecepcionarLoteRPS.EnviarLoteRpsEnvioResponse1 retVal = ((NFSe.bethaRecepcionarLoteRPS.RecepcionarLoteRps)(this)).EnviarLoteRpsEnvio(inValue);
            return retVal.EnviarLoteRpsEnvioResponse;
        }
    }
}
